# Generated by Django 4.0.2 on 2022-03-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('number1', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('email1', models.EmailField(max_length=254)),
                ('address', models.CharField(help_text='company location', max_length=200)),
                ('cont', models.CharField(default='CONTACT', max_length=50)),
                ('hm', models.CharField(default='HOME', max_length=50)),
                ('ab', models.CharField(default='ABOUT', max_length=50)),
                ('ser', models.CharField(default='SERVICES', max_length=50)),
                ('tes', models.CharField(default='TESTIMONIALS', max_length=50)),
                ('te', models.CharField(default='OUR TEAM', max_length=50)),
                ('pr', models.CharField(default='OUR COMPETING PRICES', max_length=50)),
            ],
        ),
    ]
