# Generated by Django 4.0.2 on 2022-03-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0002_company_image_company_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='slight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(help_text='what is the company about', max_length=150)),
                ('text', models.TextField(help_text='explain in short')),
                ('image', models.ImageField(upload_to='slight')),
            ],
        ),
    ]
