# Generated by Django 4.0.2 on 2022-03-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0003_slight'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(help_text='what is the company about', max_length=300)),
                ('fact', models.TextField()),
                ('fact1', models.TextField()),
                ('fact2', models.TextField()),
                ('how', models.TextField(help_text='who and who founded the firm')),
            ],
        ),
    ]
