# Generated by Django 4.0.2 on 2022-03-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0004_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='AboutDetails',
        ),
    ]
