# Generated by Django 4.0.2 on 2022-03-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0006_why_whypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='whypoint',
            name='head',
            field=models.CharField(default='efficiency', help_text='what', max_length=100),
        ),
    ]
