# Generated by Django 4.0.2 on 2022-03-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0007_whypoint_head'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='why',
            new_name='whyus',
        ),
    ]
