# Generated by Django 4.0.2 on 2022-03-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0008_rename_why_whyus'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(help_text='what they offer', max_length=80)),
                ('how', models.TextField(help_text='description of what they do.')),
            ],
        ),
    ]
