# Generated by Django 4.0.2 on 2022-03-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0009_servicedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(help_text='who made the comment', max_length=20)),
                ('office', models.CharField(help_text='what office is he', max_length=20)),
                ('image', models.ImageField(upload_to='testimony')),
                ('what', models.TextField(help_text='what did he say about the company')),
            ],
        ),
    ]
