# Generated by Django 4.0.2 on 2022-03-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0010_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='office',
            field=models.CharField(help_text='what office is he', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='who',
            field=models.CharField(help_text='who made the comment', max_length=100),
        ),
    ]
