# Generated by Django 4.0.2 on 2022-03-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwork', '0013_qanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(default='your thought', max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=10000)),
                ('im', models.ImageField(upload_to='comment')),
            ],
        ),
    ]
